### ISSUE TITLE
KeyError: 'title'

### ISSUE THREAD

**Issue by aalbright2** [benhowes/gfm-diagram#3]
Hi, I'm trying to get this action set up and I think I have it configured properly but I seem to be getting an error. This also occurs when I try to use the `outline_test.md` file so I think something might be broken?

Let me know if there's other info I can provide, here's the full error output.

```
Processing diablo-athena-to-sql/README.md... Syncing... 
Traceback (most recent call last):
Unable to sync diablo-athena-to-sql/README.md due to missing required metadata.
  File "/usr/local/bin/gfmd", line 8, in <module>
    sys.exit(run())
  File "/usr/local/lib/python3.8/site-packages/gfmd/__main__.py", line 167, in run
    process_file(file)
  File "/usr/local/lib/python3.8/site-packages/gfmd/__main__.py", line 57, in process_file
    title=document["title"],
  File "/usr/local/lib/python3.8/site-packages/frontmatter/__init__.py", line 275, in __getitem__
    return self.metadata[name]
KeyError: 'title'
```

**Comment by bonqus** [comment]
If you take a look at the demo file
https://github.com/benhowes/outline-sync-action/blob/main/demo/outline_test.md
You will see that you need to add (as the error describes) a title key:
``` md
---
title: title
---
```
